version: '3'

services:
  webserver:
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - app

  mongo:
    image: mongo:3.6.4
    command: mongod --auth --smallfiles --quiet
    environment:
      - RAILS_ENV=${ENVIRONMENT}
      - RACK_ENV=${ENVIRONMENT}
    ports:
      - "27017:27017"
    volumes:
      - 'mongo:/data/db'

  redis:
    image: 'redis:latest'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    build: .
    restart: always
    command: bundle exec sidekiq
    depends_on:
      - redis
    tty: true
    environment:
      - RAILS_ENV=${ENVIRONMENT}
    stdin_open: true
    volumes:
      - .:/app
  mailcatcher:
    image: hinshun/mailcatcher
    ports:
      - 1080:1080

  app:
    build: .
    restart: always
    depends_on:
      - 'mongo'
      - 'redis'
      - 'sidekiq'
    environment:
      - RAILS_ENV=${ENVIRONMENT}
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    command: rails s --port 3000 --binding 0.0.0.0
    tmpfs:
      - /app/tmp/pids
    links:
     - 'mailcatcher'

volumes:
  redis:
  mongo:
